apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: p2
  namespace: staging
spec:
  selector:
    matchLabels:
      app: p2
  template:
    metadata:
      labels:
        app: p2
        version: v1
    spec:
      containers:
      - name: p2
        image: manojg0521/9spokes-challenge:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-p2
  name: hello-p2
  namespace: staging
spec:
  ports:
  - port: 80
    name: http
    targetPort: 8080
  - port: 443
    name: https
    targetPort: 8080
  selector:
    app: p2
  sessionAffinity: None
  type: LoadBalancer
